BTD_BanksInfo =
{
	["BANK_UNKEMPT_1"] = BANK_UNKEMPT,
	["BANK_TREANT_THICKET_1"] = BANK_TREANT_THICKET,
	["BANK_NAGA_TEMPLE_1"] = BANK_NAGA_TEMPLE,
	["BANK_DWARVEN_TREASURE_1"] = BANK_DWARVEN_TREASURE,
	["BANK_DWARVEN_TREASURE_2"] = BANK_DWARVEN_TREASURE,
	["BANK_TREANT_THICKET_2"] = BANK_TREANT_THICKET,
	["BANK_DEMOLISH_1"] = BANK_DEMOLISH,
	["BANK_DWARVEN_TREASURE_3"] = BANK_DWARVEN_TREASURE,
	["BANK_SUNKEN_TEMPLE_1"] = BANK_SUNKEN_TEMPLE,
	["BANK_DWARVEN_TREASURE_4"] = BANK_DWARVEN_TREASURE,
	["BANK_DRAGON_UTOPIA_1"] = BANK_DRAGON_UTOPIA,
	["BANK_SUNKEN_TEMPLE_2"] = BANK_SUNKEN_TEMPLE,
	["BANK_DWARVEN_TREASURE_5"] = BANK_DWARVEN_TREASURE,
	["BANK_SUNKEN_TEMPLE_3"] = BANK_SUNKEN_TEMPLE,
	["BANK_GARGOYLE_STONEVAULT_1"] = BANK_GARGOYLE_STONEVAULT,
	["BANK_DRAGON_UTOPIA_2"] = BANK_DRAGON_UTOPIA,
	["BANK_UNKEMPT_2"] = BANK_UNKEMPT,
	["BANK_DEMOLISH_2"] = BANK_DEMOLISH,
}

BTD_NewObjects =
{
	["BTD_STATUE_OF_REVELATION_1"] = BTD_STATUE_OF_REVELATION,
	["BTD_WARMEN_HOUSE_1"] = BTD_WARMEN_HOUSE,
}

